### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by TZ0385** [emo-crab/observer_ward#304]
![image](https://github.com/emo-crab/observer_ward/assets/44598912/8d53b1a7-e3ad-490f-8a4c-7e8eda2d01f0)
师傅   请问这是个什么问题

**Comment by cn-kali-team** [comment]
URI那个前后是否存在不可见字符，或者将文件另存为ANSI编码

最后那个调用nuclei验证漏洞的，需要系统先安装nuclei到path环境变量

**Comment by TZ0385** [comment]
好的 谢谢您
