### ISSUE TITLE
批量扫描时不会打印当前进度

### ISSUE THREAD

**Issue by Shea-Des** [emo-crab/observer_ward#305]
![image](https://github.com/emo-crab/observer_ward/assets/69289278/397b334c-e30c-4492-8e71-7b741b66dd36)
如图，希望加入扫描进度状态，或者打印当前扫描任务

**Comment by cn-kali-team** [comment]
确实，今晚选个进度条再加上

**Comment by cn-kali-team** [comment]
更新了，还是再打印一次吧，如果使用进度条又一起输出日志，进度条会截断
