### ISSUE TITLE
以前的指纹如何转化为现在的格式

### ISSUE THREAD

**Issue by sv3nbeast** [emo-crab/observer_ward#306]
web_fingerprint_v3.json

**Comment by pykiller** [comment]
> 忘记留代码了，只转了公开的，如果你自己有旧版本的指纹可以转到新版的关键词匹配就可以了和favicon类型的就可以了，之前的关键词都是and关系的，也就是全部匹配才算命中，如果相同组件有多个指纹都只有一个关键词可以合并到一个新指纹里，使用or关系。

老哥v4的关键字是or关系，怎么搞
