### ISSUE TITLE
how to use own finger with --probe-dir and default web_fingerprint_v4.json together 

### ISSUE THREAD

**Issue by passwa11** [emo-crab/observer_ward#307]

**Comment by cn-kali-team** [comment]
你可以下载fingerprinthub的web-fingerprint文件夹到你本地，--probe-dir支持指定多个yaml目录
就像
observer_ward --probe-dir web-fingerprint --probe-dir 你自己的yaml文件夹 -t 目标

也可以将多个yaml目录转换为一个单文件web_fingerprint_v4.json

observer_ward --probe-dir web-fingerprint --probe-dir 你自己的yaml文件夹 -p 要保存的json文件路径

然后再将这个生成的json文件覆盖掉默认的web_fingerprint_v4.json

**Comment by passwa11** [comment]
that's great! maybe u should update this at readme.md

**Comment by cn-kali-team** [comment]
有写啊，更新指纹下面就有文档，就在调试模式的上一行
