### ISSUE TITLE
新版本保存的json结果一言难尽

### ISSUE THREAD

**Issue by zeroChen00** [emo-crab/observer_ward#310]
json里面啥都有，dict套dict、dict套list、list套dict...
原来的多简洁啊，提取信息也方便。现在做全了，输出的json反而没法用了

**Comment by cn-kali-team** [comment]
加上`--or`和`--oc`忽略部分数据

**Comment by cn-kali-team** [comment]
原来的结果没有子路径，如果在`http://127.0.0.1/nacos/`下面发现nacos，而结果里只返回`http://127.0.0.1/`，传到nuclei就识别不出来漏洞，只能改nuclei的插件。
添加证书数据是计划再后面添加cdn和waf的识别。
添加请求响应是减少对目标重复请求，返回更多数据是让其他开发者可以根据自己需要解析结果，可以不用但是不能没有。

**Comment by zeroChen00** [comment]
了解！
