### ISSUE TITLE
扫描结果缺失

### ISSUE THREAD

**Issue by zeroChen00** [emo-crab/observer_ward#311]
1900+url，存活1000+，扫描结果只有170行

![Snipaste_2024-07-17_15-03-54](https://github.com/user-attachments/assets/2c801bb3-e489-4527-9052-d454387c1b98)

**Comment by cn-kali-team** [comment]
由于发起请求的slinger不是异步的，线程池没忘记限制导致 I/O 等性能不可中断状态，大批量目标先用旧版本的或者将目标拆分一下，可能需要等到我将slinger支持异步才能解决这个问题
