### ISSUE TITLE
如何识别服务

### ISSUE THREAD

**Issue by enomothem** [emo-crab/observer_ward#313]
我看到介绍中可以识别服务端口，实用nmap探针，为何我无法识别处22端口
```
observer_ward -t tcp://x.com:22
```

**Comment by enomothem** [comment]
![image](https://github.com/user-attachments/assets/a7f05990-2b98-464c-ad35-3598bdfd2f52)
我在样例中发现有22的yaml，但是也没有识别成功

**Comment by cn-kali-team** [comment]
由于服务指纹太多正则表达式，默认是没更新到本地的，你可以试试把，https://github.com/0x727/FingerprintHub克隆到本地，然后
/observer_ward_amd64 -t tcp://127.0.0.1:22 --probe-dir FingerprintHub/service-fingerprint/null
其中`null`目录是空探针，也就是直接读取banner进行匹配，其他目录我还在写根据端口排序优先使用探针目录
如果全部探针加载完需要处理上万条规则，合并后也要发送136个请求，这会很慢

**Comment by enomothem** [comment]
明白了，nmap的指纹确实不错，正则应该不太影响速度吧，速度可以慢点，指纹这一块是个细活，探出端口任意，认出来难呀😂
