### ISSUE TITLE
新版本是否可以增加兼容web_fingerprint_v3.json旧版指纹的功能？

### ISSUE THREAD

**Issue by tr0uble-mAker** [emo-crab/observer_ward#323]
如题，旧版写了很多指纹，新版不能用了，emm

**Comment by cn-kali-team** [comment]
emm,你们怎么不提交到fingerprinthub,我只转了公开的指纹,等我有空再写转换工具吧

**Comment by JackeyLov5** [comment]
> 要不把指纹发给我，我转完同步到fingerprinthub?

师傅可以整个 方便加指纹并且自动去重的工具吗 这个跟以前的那些指纹格式不太一样 但是感觉observer更优秀误报没那么多。就想一直用下去了。thx

**Comment by charis3306** [comment]
师傅新版本的界面太花了，可以恢复以前的表格样式吗。
