### ISSUE TITLE
存在返回为200.。但是存在 window.location.href跳转的匹配匹配不到的情况

### ISSUE THREAD

**Issue by 0xelope** [emo-crab/observer_ward#340]
存在返回为200.。但是存在 window.location.href跳转的匹配匹配不到的情况

**Comment by cn-kali-team** [comment]
HTML还是js跳转的？方便发个目标或者调试信息到我邮箱吗？

**Comment by cn-kali-team** [comment]
更新了，等ci跑完就可以下载了，感谢反馈
https://github.com/emo-crab/observer_ward/actions/runs/11431599820
